/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import DB.Go;
import Entity.User;
import java.awt.Frame;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import librarysystem_dit092.Tools;
import sun.security.util.Password;
import Entity.Library;
import Forms.UserSearchByName;

/**
 *
 * @author majeddalain
 */
public class UserMainFrame extends javax.swing.JFrame {

    /**
     * Creates new form UserFrame
     */
    
    
    Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    public static String authorName,bookTitle;

    public UserMainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonUserSearch = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtUserPageName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtUserPageAddress = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtUserPagePhone = new javax.swing.JTextField();
        btnShowFinesUserPage = new javax.swing.JButton();
        butDelayedBooks = new javax.swing.JButton();
        btnLoanHistory = new javax.swing.JButton();
        UserLogOut = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rdbutSearchName = new javax.swing.JRadioButton();
        rdbutSearchTitle = new javax.swing.JRadioButton();
        btnSearchUserPage = new javax.swing.JButton();
        txtSearchUserPage = new javax.swing.JTextField();
        userpage = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 102));
        setIconImage(getIconImage());
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(97, 212, 195));

        jLabel2.setFont(new java.awt.Font("Bangla MN", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("User Name:");

        txtUserPageName.setEditable(false);
        txtUserPageName.setSelectedTextColor(new java.awt.Color(255, 0, 0));
        txtUserPageName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserPageNameActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Bangla MN", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Address:");

        txtUserPageAddress.setEditable(false);

        jLabel3.setFont(new java.awt.Font("Bangla MN", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Phone No:");

        txtUserPagePhone.setEditable(false);

        btnShowFinesUserPage.setForeground(new java.awt.Color(36, 47, 65));
        btnShowFinesUserPage.setText("Show Fines");
        btnShowFinesUserPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowFinesUserPageActionPerformed(evt);
            }
        });

        butDelayedBooks.setForeground(new java.awt.Color(36, 47, 65));
        butDelayedBooks.setText("Delayed Books");
        butDelayedBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butDelayedBooksActionPerformed(evt);
            }
        });

        btnLoanHistory.setForeground(new java.awt.Color(36, 47, 65));
        btnLoanHistory.setText("Loan History");
        btnLoanHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoanHistoryActionPerformed(evt);
            }
        });

        UserLogOut.setForeground(new java.awt.Color(36, 47, 65));
        UserLogOut.setText("Log Out");
        UserLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserLogOutActionPerformed(evt);
            }
        });

        jButton1.setText("Reallocate Book");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUserPageAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                            .addComponent(txtUserPageName)
                            .addComponent(txtUserPagePhone)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnShowFinesUserPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(butDelayedBooks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLoanHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(UserLogOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(21, 21, 21)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtUserPageName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtUserPageAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtUserPagePhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(93, 93, 93)
                .addComponent(btnShowFinesUserPage)
                .addGap(12, 12, 12)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(butDelayedBooks)
                .addGap(18, 18, 18)
                .addComponent(btnLoanHistory)
                .addGap(18, 18, 18)
                .addComponent(UserLogOut)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(36, 47, 65));

        jLabel1.setFont(new java.awt.Font("Bangla MN", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Search By: ");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        rdbutSearchName.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        rdbutSearchName.setForeground(new java.awt.Color(255, 255, 255));
        rdbutSearchName.setSelected(true);
        rdbutSearchName.setText("AuthorName");

        rdbutSearchTitle.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        rdbutSearchTitle.setForeground(new java.awt.Color(255, 255, 255));
        rdbutSearchTitle.setText("Book Title");

        btnSearchUserPage.setBackground(new java.awt.Color(51, 0, 204));
        btnSearchUserPage.setForeground(new java.awt.Color(255, 51, 0));
        btnSearchUserPage.setText("Search");
        btnSearchUserPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchUserPageActionPerformed(evt);
            }
        });

        txtSearchUserPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchUserPageActionPerformed(evt);
            }
        });

        userpage.setFont(new java.awt.Font("Times", 3, 24)); // NOI18N
        userpage.setForeground(new java.awt.Color(255, 255, 255));
        userpage.setIcon(new javax.swing.ImageIcon("/Users/majeddalain/Desktop/Icons png/man.png")); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon("/Users/majeddalain/Desktop/Icons png/booksearch.png")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(rdbutSearchName))
                            .addComponent(txtSearchUserPage, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnSearchUserPage))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(rdbutSearchTitle)))
                        .addGap(67, 67, 67))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(102, 102, 102)
                        .addComponent(jLabel5)
                        .addGap(58, 58, 58))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(userpage)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(userpage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbutSearchTitle)
                    .addComponent(rdbutSearchName)
                    .addComponent(jLabel1))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchUserPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchUserPage))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoanHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoanHistoryActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Tools.openForm(new AllUserBooks());
    }//GEN-LAST:event_btnLoanHistoryActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        buttonUserSearch.add(rdbutSearchName);
        buttonUserSearch.add(rdbutSearchTitle);
        conn = Go.setConnection();
        
        try {
        String sql = "SELECT member_name, member_address,member_phone_number FROM member WHERE member_id =?";
        pst=conn.prepareStatement(sql);
        pst.setString(1,MainLogIn.Id);
        rs = pst.executeQuery();
        if(rs.next()){
            String name = rs.getString(1);
            txtUserPageName.setText(name);
            String address = rs.getString(2);
            txtUserPageAddress.setText(address);
            String phoneNo = rs.getString(3);
            txtUserPagePhone.setText(phoneNo);
        }
        conn.close();
        
        } catch (SQLException ex) {
            
            Tools.msgBox(ex.getMessage());
        }
        
        
    }//GEN-LAST:event_formWindowOpened

    private void UserLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserLogOutActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Tools.openForm(new MainLogIn());
        
    }//GEN-LAST:event_UserLogOutActionPerformed

    private void txtUserPageNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserPageNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserPageNameActionPerformed

    private void butDelayedBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butDelayedBooksActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Tools.openForm(new delayedBooks());
    }//GEN-LAST:event_butDelayedBooksActionPerformed

    private void btnShowFinesUserPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowFinesUserPageActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Tools.openForm(new UserFines());
       
    }//GEN-LAST:event_btnShowFinesUserPageActionPerformed

    private void txtSearchUserPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchUserPageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchUserPageActionPerformed

    private void btnSearchUserPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchUserPageActionPerformed
        // TODO add your handling code here:

        if(rdbutSearchName.isSelected()){
            authorName = txtSearchUserPage.getText();
            this.dispose();
            Tools.openForm(new UserSearchByName());

        }
        else if(rdbutSearchTitle.isSelected()) {
            bookTitle = txtSearchUserPage.getText();
            this.dispose();
            Tools.openForm(new UserSearchByTitle());

        }
    }//GEN-LAST:event_btnSearchUserPageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserMainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton UserLogOut;
    private javax.swing.JButton btnLoanHistory;
    private javax.swing.JButton btnSearchUserPage;
    private javax.swing.JButton btnShowFinesUserPage;
    private javax.swing.JButton butDelayedBooks;
    private javax.swing.ButtonGroup buttonUserSearch;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton rdbutSearchName;
    private javax.swing.JRadioButton rdbutSearchTitle;
    private javax.swing.JTextField txtSearchUserPage;
    private javax.swing.JTextField txtUserPageAddress;
    private javax.swing.JTextField txtUserPageName;
    private javax.swing.JTextField txtUserPagePhone;
    private javax.swing.JLabel userpage;
    // End of variables declaration//GEN-END:variables
}
